import { Test, TestingModule } from '@nestjs/testing';
import { GitHubService } from './github.service';

// Mock the @octokit/rest module
jest.mock('@octokit/rest', () => ({
  Octokit: jest.fn().mockImplementation(() => ({
    users: {
      getAuthenticated: jest.fn(),
    },
    repos: {
      createForAuthenticatedUser: jest.fn(),
      createOrUpdateFileContents: jest.fn(),
    },
  })),
}));

describe('GitHubService', () => {
  let service: GitHubService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [GitHubService],
    }).compile();

    service = module.get<GitHubService>(GitHubService);
  });

  describe('sanitizeRepositoryName', () => {
    it('should convert spaces to hyphens', () => {
      const result = service.sanitizeRepositoryName('My Awesome Project');
      expect(result).toBe('my-awesome-project');
    });

    it('should remove invalid characters', () => {
      const result = service.sanitizeRepositoryName('Project@#$%Name!');
      expect(result).toBe('projectname');
    });

    it('should remove leading hyphens', () => {
      const result = service.sanitizeRepositoryName('---project-name');
      expect(result).toBe('project-name');
    });

    it('should limit length to 100 characters', () => {
      const longName = 'a'.repeat(150);
      const result = service.sanitizeRepositoryName(longName);
      expect(result.length).toBe(100);
    });

    it('should return default name for empty input', () => {
      const result = service.sanitizeRepositoryName('');
      expect(result).toBe('techmate-project');
    });

    it('should return default name for invalid-only characters', () => {
      const result = service.sanitizeRepositoryName('@#$%^&*()');
      expect(result).toBe('techmate-project');
    });
  });

  describe('generateReadme', () => {
    it('should generate README with all sections', () => {
      const readme = service.generateReadme(
        'Test Project',
        'A test project description',
        ['React', 'TypeScript', 'Node.js'],
        [
          { title: 'Setup', description: 'Initialize project' },
          { title: 'Build', description: 'Build the application' },
        ],
      );

      expect(readme).toContain('# Test Project');
      expect(readme).toContain('A test project description');
      expect(readme).toContain('## Tech Stack');
      expect(readme).toContain('- React');
      expect(readme).toContain('- TypeScript');
      expect(readme).toContain('- Node.js');
      expect(readme).toContain('## Implementation Tasks');
      expect(readme).toContain('1. **Setup**: Initialize project');
      expect(readme).toContain('2. **Build**: Build the application');
      expect(readme).toContain('Generated by TechMate AI');
    });

    it('should handle empty technologies array', () => {
      const readme = service.generateReadme(
        'Test Project',
        'Description',
        [],
        [],
      );

      expect(readme).toContain('# Test Project');
      expect(readme).toContain('Description');
      expect(readme).not.toContain('## Tech Stack');
    });

    it('should handle empty tasks array', () => {
      const readme = service.generateReadme(
        'Test Project',
        'Description',
        ['React'],
        [],
      );

      expect(readme).toContain('# Test Project');
      expect(readme).not.toContain('## Implementation Tasks');
    });
  });
});
