import { Injectable, Logger, BadRequestException } from '@nestjs/common';
import { Octokit } from '@octokit/rest';

/**
 * Service for GitHub API integration
 * Handles repository creation, file uploads, and README generation
 */
@Injectable()
export class GitHubService {
  private readonly logger = new Logger(GitHubService.name);

  /**
   * Create a GitHub client with the provided access token
   */
  private createClient(accessToken: string): Octokit {
    return new Octokit({
      auth: accessToken,
    });
  }

  /**
   * Get the authenticated user's GitHub username
   */
  async getAuthenticatedUser(accessToken: string): Promise<string> {
    try {
      const octokit = this.createClient(accessToken);
      const { data } = await octokit.users.getAuthenticated();
      return data.login;
    } catch (error) {
      this.logger.error('Failed to get authenticated user', error);
      throw new BadRequestException(
        'Invalid GitHub token or authentication failed',
      );
    }
  }

  /**
   * Create a new GitHub repository
   */
  async createRepository(
    accessToken: string,
    name: string,
    description: string,
    isPrivate: boolean,
  ): Promise<{ owner: string; repo: string; url: string }> {
    try {
      const octokit = this.createClient(accessToken);

      this.logger.log(`Creating GitHub repository: ${name}`);

      const { data } = await octokit.repos.createForAuthenticatedUser({
        name,
        description,
        private: isPrivate,
        auto_init: false, // We'll add files manually
      });

      this.logger.log(
        `Successfully created repository: ${data.owner.login}/${data.name}`,
      );

      return {
        owner: data.owner.login,
        repo: data.name,
        url: data.html_url,
      };
    } catch (error: any) {
      this.logger.error('Failed to create GitHub repository', error);

      if (error.status === 422) {
        throw new BadRequestException(
          'Repository name already exists or is invalid',
        );
      }

      throw new BadRequestException(
        'Failed to create GitHub repository. Please check your token permissions.',
      );
    }
  }

  /**
   * Upload files to a GitHub repository
   * Uses the GitHub Contents API to create files
   */
  async uploadFiles(
    accessToken: string,
    owner: string,
    repo: string,
    files: Array<{ path: string; content: string }>,
  ): Promise<void> {
    const octokit = this.createClient(accessToken);

    this.logger.log(`Uploading ${files.length} files to ${owner}/${repo}`);

    // Upload files sequentially to avoid rate limiting issues
    for (const file of files) {
      try {
        // Encode content to base64
        const contentEncoded = Buffer.from(file.content).toString('base64');

        await octokit.repos.createOrUpdateFileContents({
          owner,
          repo,
          path: file.path,
          message: `Add ${file.path}`,
          content: contentEncoded,
        });

        this.logger.log(`Uploaded file: ${file.path}`);
      } catch (error) {
        this.logger.error(`Failed to upload file: ${file.path}`, error);
        throw new BadRequestException(
          `Failed to upload file: ${file.path}. Please try again.`,
        );
      }
    }

    this.logger.log(`Successfully uploaded all files to ${owner}/${repo}`);
  }

  /**
   * Generate a README.md file for the project
   */
  generateReadme(
    projectTitle: string,
    projectDescription: string,
    technologies: string[],
    tasks: Array<{ title: string; description: string }>,
  ): string {
    const techStackSection = technologies.length > 0
      ? `## Tech Stack

${technologies.map((tech) => `- ${tech}`).join('\n')}
`
      : '';

    const tasksSection = tasks.length > 0
      ? `## Implementation Tasks

${tasks.map((task, index) => `${index + 1}. **${task.title}**: ${task.description}`).join('\n')}
`
      : '';

    return `# ${projectTitle}

${projectDescription}

${techStackSection}
## Getting Started

1. Clone this repository
2. Install dependencies
3. Follow the implementation tasks below

${tasksSection}
## Generated by TechMate AI

This project was generated by [TechMate AI](https://techmate.ai), an AI-powered tech mentorship platform.

## License

MIT
`;
  }

  /**
   * Sanitize repository name to meet GitHub requirements
   * - Only alphanumeric characters, hyphens, and underscores
   * - Cannot start with a hyphen
   * - Maximum 100 characters
   */
  sanitizeRepositoryName(name: string): string {
    // Convert to lowercase and replace spaces with hyphens
    let sanitized = name.toLowerCase().replace(/\s+/g, '-');

    // Remove invalid characters
    sanitized = sanitized.replace(/[^a-z0-9-_]/g, '');

    // Remove leading hyphens
    sanitized = sanitized.replace(/^-+/, '');

    // Limit length
    sanitized = sanitized.substring(0, 100);

    // Ensure it's not empty
    if (!sanitized) {
      sanitized = 'techmate-project';
    }

    return sanitized;
  }
}
