import {
  IsUUID,
  IsString,
  IsOptional,
  IsBoolean,
  MaxLength,
  MinLength,
  Matches,
} from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';
import { Transform } from 'class-transformer';

export class ExportGitHubDto {
  @ApiProperty({
    description: 'Project architecture ID to export',
    example: '123e4567-e89b-12d3-a456-426614174000',
  })
  @IsUUID('4', { message: 'Architecture ID must be a valid UUID' })
  architectureId: string;

  @ApiProperty({
    description: 'GitHub access token for authentication',
    example: 'ghp_xxxxxxxxxxxxxxxxxxxx',
  })
  @IsString()
  @MinLength(10, { message: 'GitHub token must be at least 10 characters' })
  @MaxLength(200, { message: 'GitHub token must not exceed 200 characters' })
  githubToken: string;

  @ApiProperty({
    description: 'Repository name (optional, defaults to project title)',
    example: 'my-awesome-project',
    required: false,
  })
  @IsOptional()
  @IsString()
  @MinLength(1, { message: 'Repository name must not be empty' })
  @MaxLength(100, {
    message: 'Repository name must not exceed 100 characters',
  })
  @Matches(/^[a-zA-Z0-9_-]+$/, {
    message:
      'Repository name can only contain letters, numbers, hyphens, and underscores',
  })
  @Transform(({ value }) => value?.trim())
  repositoryName?: string;

  @ApiProperty({
    description: 'Repository description (optional)',
    example: 'An awesome project generated by TechMate AI',
    required: false,
  })
  @IsOptional()
  @IsString()
  @MaxLength(500, {
    message: 'Description must not exceed 500 characters',
  })
  @Transform(({ value }) => value?.trim())
  description?: string;

  @ApiProperty({
    description: 'Whether the repository should be private',
    example: false,
    required: false,
    default: false,
  })
  @IsOptional()
  @IsBoolean()
  isPrivate?: boolean;
}
